@endpoint = http://localhost:8000

GET {{endpoint}}/movies

###

GET {{endpoint}}/movies/1
# {
#     "id": 1,
#     "title": "ターミネーター",
#     "overview": "シュワちゃんカッコいい!!",
#     "genres": [
#         {
#         "code": "action",
#         "name": "アクション"
#         },
#         {
#         "code": "horror",
#         "name": "ホラー"
#         },
#         {
#         "code": "sf",
#         "name": "SF"
#         }
#     ]
# }


###

GET {{endpoint}}/movies/4
# {
#     "id": 4,
#     "title": "ターミネーター4",
#     "overview": "マーカス!!",
#     "genres": [
#         {
#             "code": "action",
#             "name": "アクション"
#         },
#         {
#             "code": "drama",
#             "name": "ドラマ"
#         },
#         {
#             "code": "horror",
#             "name": "ホラー"
#         },
#         {
#             "code": "sf",
#             "name": "SF"
#         },
#         {
#             "code": "war",
#             "name": "戦争"
#         }
#     ]
# }

###

POST {{endpoint}}/movie
content-type: application/json

{
    "title": "テストの映画",
    "overview": "概要は割と適当です...",
    "genres": []
}

###

POST {{endpoint}}/movie
content-type: application/json

{
    "overview": "概要は割と適当です...",
    "genres": []
}

###

POST {{endpoint}}/movie
content-type: application/json

{
    "test_title": "パラメータの指定が間違えています"
}
