// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMovie = "movie"

// Movie mapped from table <movie>
type Movie struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	Title     string    `gorm:"column:title;not null" json:"title"`
	Overview  string    `gorm:"column:overview" json:"overview"`
	Genres    []Genre   `gorm:"many2many:movie_genre" json:"genres"`
}

// TableName Movie's table name
func (*Movie) TableName() string {
	return TableNameMovie
}
