version: "3"

services:
  api:
    container_name: golang_tutorial_api
    build:
      context: .
      args:
        - WITH_GOTEST=1
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
    command: >
      bash -c  'go run server.go'
    env_file:
      - .env

  db:
    image: mysql:8.0.32
    container_name: golang_tutorial_db
    ports:
      - 3306:3306
    volumes:
      - mysql-volumes:/var/lib/mysql
      - ./mysql/entrypoint/:/docker-entrypoint-initdb.d
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "db4test"

volumes:
  mysql-volumes:
