// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMovieGenre = "movie_genre"

// MovieGenre mapped from table <movie_genre>
type MovieGenre struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	MovieID   int32     `gorm:"column:movie_id;not null" json:"movie_id"`
	GenreID   int32     `gorm:"column:genre_id;not null" json:"genre_id"`
}

// TableName MovieGenre's table name
func (*MovieGenre) TableName() string {
	return TableNameMovieGenre
}
