// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMovieNeo = "movie_neo"

// MovieNeo mapped from table <movie_neo>
type MovieNeo struct {
	ID         int32      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt  time.Time  `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  time.Time  `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	Title      string     `gorm:"column:title;not null" json:"title"`
	Overview   string     `gorm:"column:overview" json:"overview"`
	Genres_neo []GenreNeo `gorm:"foreignKey:MovieRefer;references:ID" json:"genres_neo"`
}

// TableName MovieNeo's table name
func (*MovieNeo) TableName() string {
	return TableNameMovieNeo
}
