// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"golang_tutorial/src/model"
)

func newGenreNeo(db *gorm.DB, opts ...gen.DOOption) genreNeo {
	_genreNeo := genreNeo{}

	_genreNeo.genreNeoDo.UseDB(db, opts...)
	_genreNeo.genreNeoDo.UseModel(&model.GenreNeo{})

	tableName := _genreNeo.genreNeoDo.TableName()
	_genreNeo.ALL = field.NewAsterisk(tableName)
	_genreNeo.ID = field.NewInt32(tableName, "id")
	_genreNeo.CreatedAt = field.NewTime(tableName, "created_at")
	_genreNeo.UpdatedAt = field.NewTime(tableName, "updated_at")
	_genreNeo.Code = field.NewString(tableName, "code")
	_genreNeo.Name = field.NewString(tableName, "name")
	_genreNeo.MovieID = field.NewInt32(tableName, "movie_id")

	_genreNeo.fillFieldMap()

	return _genreNeo
}

type genreNeo struct {
	genreNeoDo

	ALL       field.Asterisk
	ID        field.Int32
	CreatedAt field.Time
	UpdatedAt field.Time
	Code      field.String
	Name      field.String
	MovieID   field.Int32

	fieldMap map[string]field.Expr
}

func (g genreNeo) Table(newTableName string) *genreNeo {
	g.genreNeoDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g genreNeo) As(alias string) *genreNeo {
	g.genreNeoDo.DO = *(g.genreNeoDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *genreNeo) updateTableName(table string) *genreNeo {
	g.ALL = field.NewAsterisk(table)
	g.ID = field.NewInt32(table, "id")
	g.CreatedAt = field.NewTime(table, "created_at")
	g.UpdatedAt = field.NewTime(table, "updated_at")
	g.Code = field.NewString(table, "code")
	g.Name = field.NewString(table, "name")
	g.MovieID = field.NewInt32(table, "movie_id")

	g.fillFieldMap()

	return g
}

func (g *genreNeo) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *genreNeo) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 6)
	g.fieldMap["id"] = g.ID
	g.fieldMap["created_at"] = g.CreatedAt
	g.fieldMap["updated_at"] = g.UpdatedAt
	g.fieldMap["code"] = g.Code
	g.fieldMap["name"] = g.Name
	g.fieldMap["movie_id"] = g.MovieID
}

func (g genreNeo) clone(db *gorm.DB) genreNeo {
	g.genreNeoDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g genreNeo) replaceDB(db *gorm.DB) genreNeo {
	g.genreNeoDo.ReplaceDB(db)
	return g
}

type genreNeoDo struct{ gen.DO }

func (g genreNeoDo) Debug() *genreNeoDo {
	return g.withDO(g.DO.Debug())
}

func (g genreNeoDo) WithContext(ctx context.Context) *genreNeoDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g genreNeoDo) ReadDB() *genreNeoDo {
	return g.Clauses(dbresolver.Read)
}

func (g genreNeoDo) WriteDB() *genreNeoDo {
	return g.Clauses(dbresolver.Write)
}

func (g genreNeoDo) Session(config *gorm.Session) *genreNeoDo {
	return g.withDO(g.DO.Session(config))
}

func (g genreNeoDo) Clauses(conds ...clause.Expression) *genreNeoDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g genreNeoDo) Returning(value interface{}, columns ...string) *genreNeoDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g genreNeoDo) Not(conds ...gen.Condition) *genreNeoDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g genreNeoDo) Or(conds ...gen.Condition) *genreNeoDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g genreNeoDo) Select(conds ...field.Expr) *genreNeoDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g genreNeoDo) Where(conds ...gen.Condition) *genreNeoDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g genreNeoDo) Order(conds ...field.Expr) *genreNeoDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g genreNeoDo) Distinct(cols ...field.Expr) *genreNeoDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g genreNeoDo) Omit(cols ...field.Expr) *genreNeoDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g genreNeoDo) Join(table schema.Tabler, on ...field.Expr) *genreNeoDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g genreNeoDo) LeftJoin(table schema.Tabler, on ...field.Expr) *genreNeoDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g genreNeoDo) RightJoin(table schema.Tabler, on ...field.Expr) *genreNeoDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g genreNeoDo) Group(cols ...field.Expr) *genreNeoDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g genreNeoDo) Having(conds ...gen.Condition) *genreNeoDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g genreNeoDo) Limit(limit int) *genreNeoDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g genreNeoDo) Offset(offset int) *genreNeoDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g genreNeoDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *genreNeoDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g genreNeoDo) Unscoped() *genreNeoDo {
	return g.withDO(g.DO.Unscoped())
}

func (g genreNeoDo) Create(values ...*model.GenreNeo) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g genreNeoDo) CreateInBatches(values []*model.GenreNeo, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g genreNeoDo) Save(values ...*model.GenreNeo) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g genreNeoDo) First() (*model.GenreNeo, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.GenreNeo), nil
	}
}

func (g genreNeoDo) Take() (*model.GenreNeo, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.GenreNeo), nil
	}
}

func (g genreNeoDo) Last() (*model.GenreNeo, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.GenreNeo), nil
	}
}

func (g genreNeoDo) Find() ([]*model.GenreNeo, error) {
	result, err := g.DO.Find()
	return result.([]*model.GenreNeo), err
}

func (g genreNeoDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GenreNeo, err error) {
	buf := make([]*model.GenreNeo, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g genreNeoDo) FindInBatches(result *[]*model.GenreNeo, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g genreNeoDo) Attrs(attrs ...field.AssignExpr) *genreNeoDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g genreNeoDo) Assign(attrs ...field.AssignExpr) *genreNeoDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g genreNeoDo) Joins(fields ...field.RelationField) *genreNeoDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g genreNeoDo) Preload(fields ...field.RelationField) *genreNeoDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g genreNeoDo) FirstOrInit() (*model.GenreNeo, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.GenreNeo), nil
	}
}

func (g genreNeoDo) FirstOrCreate() (*model.GenreNeo, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.GenreNeo), nil
	}
}

func (g genreNeoDo) FindByPage(offset int, limit int) (result []*model.GenreNeo, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g genreNeoDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g genreNeoDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g genreNeoDo) Delete(models ...*model.GenreNeo) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *genreNeoDo) withDO(do gen.Dao) *genreNeoDo {
	g.DO = *do.(*gen.DO)
	return g
}
