// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"golang_tutorial/src/model"
)

func newMovie(db *gorm.DB, opts ...gen.DOOption) movie {
	_movie := movie{}

	_movie.movieDo.UseDB(db, opts...)
	_movie.movieDo.UseModel(&model.Movie{})

	tableName := _movie.movieDo.TableName()
	_movie.ALL = field.NewAsterisk(tableName)
	_movie.ID = field.NewInt32(tableName, "id")
	_movie.CreatedAt = field.NewTime(tableName, "created_at")
	_movie.UpdatedAt = field.NewTime(tableName, "updated_at")
	_movie.Title = field.NewString(tableName, "title")
	_movie.Overview = field.NewString(tableName, "overview")

	_movie.fillFieldMap()

	return _movie
}

type movie struct {
	movieDo

	ALL       field.Asterisk
	ID        field.Int32
	CreatedAt field.Time
	UpdatedAt field.Time
	Title     field.String
	Overview  field.String

	fieldMap map[string]field.Expr
}

func (m movie) Table(newTableName string) *movie {
	m.movieDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m movie) As(alias string) *movie {
	m.movieDo.DO = *(m.movieDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *movie) updateTableName(table string) *movie {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt32(table, "id")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")
	m.Title = field.NewString(table, "title")
	m.Overview = field.NewString(table, "overview")

	m.fillFieldMap()

	return m
}

func (m *movie) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *movie) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 5)
	m.fieldMap["id"] = m.ID
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
	m.fieldMap["title"] = m.Title
	m.fieldMap["overview"] = m.Overview
}

func (m movie) clone(db *gorm.DB) movie {
	m.movieDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m movie) replaceDB(db *gorm.DB) movie {
	m.movieDo.ReplaceDB(db)
	return m
}

type movieDo struct{ gen.DO }

func (m movieDo) Debug() *movieDo {
	return m.withDO(m.DO.Debug())
}

func (m movieDo) WithContext(ctx context.Context) *movieDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m movieDo) ReadDB() *movieDo {
	return m.Clauses(dbresolver.Read)
}

func (m movieDo) WriteDB() *movieDo {
	return m.Clauses(dbresolver.Write)
}

func (m movieDo) Session(config *gorm.Session) *movieDo {
	return m.withDO(m.DO.Session(config))
}

func (m movieDo) Clauses(conds ...clause.Expression) *movieDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m movieDo) Returning(value interface{}, columns ...string) *movieDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m movieDo) Not(conds ...gen.Condition) *movieDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m movieDo) Or(conds ...gen.Condition) *movieDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m movieDo) Select(conds ...field.Expr) *movieDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m movieDo) Where(conds ...gen.Condition) *movieDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m movieDo) Order(conds ...field.Expr) *movieDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m movieDo) Distinct(cols ...field.Expr) *movieDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m movieDo) Omit(cols ...field.Expr) *movieDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m movieDo) Join(table schema.Tabler, on ...field.Expr) *movieDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m movieDo) LeftJoin(table schema.Tabler, on ...field.Expr) *movieDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m movieDo) RightJoin(table schema.Tabler, on ...field.Expr) *movieDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m movieDo) Group(cols ...field.Expr) *movieDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m movieDo) Having(conds ...gen.Condition) *movieDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m movieDo) Limit(limit int) *movieDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m movieDo) Offset(offset int) *movieDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m movieDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *movieDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m movieDo) Unscoped() *movieDo {
	return m.withDO(m.DO.Unscoped())
}

func (m movieDo) Create(values ...*model.Movie) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m movieDo) CreateInBatches(values []*model.Movie, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m movieDo) Save(values ...*model.Movie) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m movieDo) First() (*model.Movie, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Movie), nil
	}
}

func (m movieDo) Take() (*model.Movie, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Movie), nil
	}
}

func (m movieDo) Last() (*model.Movie, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Movie), nil
	}
}

func (m movieDo) Find() ([]*model.Movie, error) {
	result, err := m.DO.Find()
	return result.([]*model.Movie), err
}

func (m movieDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Movie, err error) {
	buf := make([]*model.Movie, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m movieDo) FindInBatches(result *[]*model.Movie, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m movieDo) Attrs(attrs ...field.AssignExpr) *movieDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m movieDo) Assign(attrs ...field.AssignExpr) *movieDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m movieDo) Joins(fields ...field.RelationField) *movieDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m movieDo) Preload(fields ...field.RelationField) *movieDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m movieDo) FirstOrInit() (*model.Movie, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Movie), nil
	}
}

func (m movieDo) FirstOrCreate() (*model.Movie, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Movie), nil
	}
}

func (m movieDo) FindByPage(offset int, limit int) (result []*model.Movie, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m movieDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m movieDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m movieDo) Delete(models ...*model.Movie) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *movieDo) withDO(do gen.Dao) *movieDo {
	m.DO = *do.(*gen.DO)
	return m
}
