// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"golang_tutorial/src/model"
)

func newMovieNeo(db *gorm.DB, opts ...gen.DOOption) movieNeo {
	_movieNeo := movieNeo{}

	_movieNeo.movieNeoDo.UseDB(db, opts...)
	_movieNeo.movieNeoDo.UseModel(&model.MovieNeo{})

	tableName := _movieNeo.movieNeoDo.TableName()
	_movieNeo.ALL = field.NewAsterisk(tableName)
	_movieNeo.ID = field.NewInt32(tableName, "id")
	_movieNeo.CreatedAt = field.NewTime(tableName, "created_at")
	_movieNeo.UpdatedAt = field.NewTime(tableName, "updated_at")
	_movieNeo.Title = field.NewString(tableName, "title")
	_movieNeo.Overview = field.NewString(tableName, "overview")
	_movieNeo.Genres_neo = movieNeoHasManyGenres_neo{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Genres_neo", "model.GenreNeo"),
	}

	_movieNeo.fillFieldMap()

	return _movieNeo
}

type movieNeo struct {
	movieNeoDo

	ALL        field.Asterisk
	ID         field.Int32
	CreatedAt  field.Time
	UpdatedAt  field.Time
	Title      field.String
	Overview   field.String
	Genres_neo movieNeoHasManyGenres_neo

	fieldMap map[string]field.Expr
}

func (m movieNeo) Table(newTableName string) *movieNeo {
	m.movieNeoDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m movieNeo) As(alias string) *movieNeo {
	m.movieNeoDo.DO = *(m.movieNeoDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *movieNeo) updateTableName(table string) *movieNeo {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt32(table, "id")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")
	m.Title = field.NewString(table, "title")
	m.Overview = field.NewString(table, "overview")

	m.fillFieldMap()

	return m
}

func (m *movieNeo) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *movieNeo) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 6)
	m.fieldMap["id"] = m.ID
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
	m.fieldMap["title"] = m.Title
	m.fieldMap["overview"] = m.Overview

}

func (m movieNeo) clone(db *gorm.DB) movieNeo {
	m.movieNeoDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m movieNeo) replaceDB(db *gorm.DB) movieNeo {
	m.movieNeoDo.ReplaceDB(db)
	return m
}

type movieNeoHasManyGenres_neo struct {
	db *gorm.DB

	field.RelationField
}

func (a movieNeoHasManyGenres_neo) Where(conds ...field.Expr) *movieNeoHasManyGenres_neo {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a movieNeoHasManyGenres_neo) WithContext(ctx context.Context) *movieNeoHasManyGenres_neo {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a movieNeoHasManyGenres_neo) Session(session *gorm.Session) *movieNeoHasManyGenres_neo {
	a.db = a.db.Session(session)
	return &a
}

func (a movieNeoHasManyGenres_neo) Model(m *model.MovieNeo) *movieNeoHasManyGenres_neoTx {
	return &movieNeoHasManyGenres_neoTx{a.db.Model(m).Association(a.Name())}
}

type movieNeoHasManyGenres_neoTx struct{ tx *gorm.Association }

func (a movieNeoHasManyGenres_neoTx) Find() (result []*model.GenreNeo, err error) {
	return result, a.tx.Find(&result)
}

func (a movieNeoHasManyGenres_neoTx) Append(values ...*model.GenreNeo) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a movieNeoHasManyGenres_neoTx) Replace(values ...*model.GenreNeo) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a movieNeoHasManyGenres_neoTx) Delete(values ...*model.GenreNeo) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a movieNeoHasManyGenres_neoTx) Clear() error {
	return a.tx.Clear()
}

func (a movieNeoHasManyGenres_neoTx) Count() int64 {
	return a.tx.Count()
}

type movieNeoDo struct{ gen.DO }

func (m movieNeoDo) Debug() *movieNeoDo {
	return m.withDO(m.DO.Debug())
}

func (m movieNeoDo) WithContext(ctx context.Context) *movieNeoDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m movieNeoDo) ReadDB() *movieNeoDo {
	return m.Clauses(dbresolver.Read)
}

func (m movieNeoDo) WriteDB() *movieNeoDo {
	return m.Clauses(dbresolver.Write)
}

func (m movieNeoDo) Session(config *gorm.Session) *movieNeoDo {
	return m.withDO(m.DO.Session(config))
}

func (m movieNeoDo) Clauses(conds ...clause.Expression) *movieNeoDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m movieNeoDo) Returning(value interface{}, columns ...string) *movieNeoDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m movieNeoDo) Not(conds ...gen.Condition) *movieNeoDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m movieNeoDo) Or(conds ...gen.Condition) *movieNeoDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m movieNeoDo) Select(conds ...field.Expr) *movieNeoDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m movieNeoDo) Where(conds ...gen.Condition) *movieNeoDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m movieNeoDo) Order(conds ...field.Expr) *movieNeoDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m movieNeoDo) Distinct(cols ...field.Expr) *movieNeoDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m movieNeoDo) Omit(cols ...field.Expr) *movieNeoDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m movieNeoDo) Join(table schema.Tabler, on ...field.Expr) *movieNeoDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m movieNeoDo) LeftJoin(table schema.Tabler, on ...field.Expr) *movieNeoDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m movieNeoDo) RightJoin(table schema.Tabler, on ...field.Expr) *movieNeoDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m movieNeoDo) Group(cols ...field.Expr) *movieNeoDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m movieNeoDo) Having(conds ...gen.Condition) *movieNeoDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m movieNeoDo) Limit(limit int) *movieNeoDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m movieNeoDo) Offset(offset int) *movieNeoDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m movieNeoDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *movieNeoDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m movieNeoDo) Unscoped() *movieNeoDo {
	return m.withDO(m.DO.Unscoped())
}

func (m movieNeoDo) Create(values ...*model.MovieNeo) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m movieNeoDo) CreateInBatches(values []*model.MovieNeo, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m movieNeoDo) Save(values ...*model.MovieNeo) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m movieNeoDo) First() (*model.MovieNeo, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MovieNeo), nil
	}
}

func (m movieNeoDo) Take() (*model.MovieNeo, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MovieNeo), nil
	}
}

func (m movieNeoDo) Last() (*model.MovieNeo, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MovieNeo), nil
	}
}

func (m movieNeoDo) Find() ([]*model.MovieNeo, error) {
	result, err := m.DO.Find()
	return result.([]*model.MovieNeo), err
}

func (m movieNeoDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MovieNeo, err error) {
	buf := make([]*model.MovieNeo, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m movieNeoDo) FindInBatches(result *[]*model.MovieNeo, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m movieNeoDo) Attrs(attrs ...field.AssignExpr) *movieNeoDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m movieNeoDo) Assign(attrs ...field.AssignExpr) *movieNeoDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m movieNeoDo) Joins(fields ...field.RelationField) *movieNeoDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m movieNeoDo) Preload(fields ...field.RelationField) *movieNeoDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m movieNeoDo) FirstOrInit() (*model.MovieNeo, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MovieNeo), nil
	}
}

func (m movieNeoDo) FirstOrCreate() (*model.MovieNeo, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MovieNeo), nil
	}
}

func (m movieNeoDo) FindByPage(offset int, limit int) (result []*model.MovieNeo, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m movieNeoDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m movieNeoDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m movieNeoDo) Delete(models ...*model.MovieNeo) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *movieNeoDo) withDO(do gen.Dao) *movieNeoDo {
	m.DO = *do.(*gen.DO)
	return m
}
