name: Go Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  ARCH: x64

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          cp .example.env .env

      - name: Build Image
        run: |
          make build

      - name: Run Container
        run: |
          docker compose --env-file .env up -d

      - name: Run Tests in Container
        run: |
          docker compose --env-file .env exec golang_tutorial_api gotest -v ./tests/... -cover
