name: Go Test

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "feat/**"

env:
  ARCH: x64

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Environment
        run: |
          cp .example/env .env

      - name: Build Image
        run: |
          make build

      - name: Run Tests in Container
        run: |
          sudo chown -R 1000:1000 ${{ github.workspace }}
          docker compose run --rm api -v ${{ github.workspace }}:/work -w /work gotest -v ./tests/... -cover
